const data=[
    {
      vehicle_id: "V001",
      no_of_trips: 40,
      trip_kms: 950,
      avg_kms_per_day: 25,
      avg_trip_per_day: 1.5,
      avg_daily_work_hour: 7,
      avg_daily_charging_time: 3,
      co2_emission: 480,
      vendor_name: "EcoMotion Motors",
      charged:90
    },
    {
      vehicle_id: "V002",
      no_of_trips: 35,
      trip_kms: 800,
      avg_kms_per_day: 20,
      avg_trip_per_day: 1.2,
      avg_daily_work_hour: 6,
      avg_daily_charging_time: 2.5,
      co2_emission: 520,
      vendor_name: "GreenRide Technologies",
      charged:80
    },
    {
      vehicle_id: "V003",
      no_of_trips: 50,
      trip_kms: 1200,
      avg_kms_per_day: 30,
      avg_trip_per_day: 2,
      avg_daily_work_hour: 8,
      avg_daily_charging_time: 4,
      co2_emission: 500,
      vendor_name: "CleanDrive Innovations",
      charged:20
    },
    {
      vehicle_id: "V004",
      no_of_trips: 45,
      trip_kms: 1100,
      avg_kms_per_day: 27,
      avg_trip_per_day: 1.8,
      avg_daily_work_hour: 7.5,
      avg_daily_charging_time: 3.5,
      co2_emission: 490,
      vendor_name: "EcoVehicles Ltd.",
       charged:80
    },
    {
      vehicle_id: "V005",
      no_of_trips: 42,
      trip_kms: 1000,
      avg_kms_per_day: 24,
      avg_trip_per_day: 1.4,
      avg_daily_work_hour: 7,
      avg_daily_charging_time: 3,
      co2_emission: 510,
      vendor_name: "Sustainable Autos",
      charged:60
    },
    {
      vehicle_id: "V006",
      no_of_trips: 38,
      trip_kms: 900,
      avg_kms_per_day: 22,
      avg_trip_per_day: 1.3,
      avg_daily_work_hour: 6.5,
      avg_daily_charging_time: 2.8,
      co2_emission: 525,
      vendor_name: "GreenWheels Corp.",
      charged:30
    },
    {
      vehicle_id: "V007",
      no_of_trips: 55,
      trip_kms: 1300,
      avg_kms_per_day: 35,
      avg_trip_per_day: 2.2,
      avg_daily_work_hour: 8.5,
      avg_daily_charging_time: 4.2,
      co2_emission: 470,
      vendor_name: "FutureDrive Solutions",
      charged:85
    },
    {
      vehicle_id: "V008",
      no_of_trips: 37,
      trip_kms: 850,
      avg_kms_per_day: 23,
      avg_trip_per_day: 1.4,
      avg_daily_work_hour: 7,
      avg_daily_charging_time: 3.2,
      co2_emission: 505,
      vendor_name: "EcoFleet Innovations",
      charged:89
    },
    {
      vehicle_id: "V009",
      no_of_trips: 48,
      trip_kms: 1150,
      avg_kms_per_day: 28,
      avg_trip_per_day: 1.7,
      avg_daily_work_hour: 7.8,
      avg_daily_charging_time: 3.8,
      co2_emission: 485,
      vendor_name: "GreenTech Motors",
      charged:55
    },
    {
      vehicle_id: "V010",
      no_of_trips: 33,
      trip_kms: 750,
      avg_kms_per_day: 18,
      avg_trip_per_day: 1.1,
      avg_daily_work_hour: 6,
      avg_daily_charging_time: 2.3,
      co2_emission: 530,
      vendor_name: "EcoFusion Autos",
      charged:20
    },
    {
      vehicle_id: "V011",
      no_of_trips: 41,
      trip_kms: 975,
      avg_kms_per_day: 26,
      avg_trip_per_day: 1.6,
      avg_daily_work_hour: 7.2,
      avg_daily_charging_time: 3.3,
      co2_emission: 495,
      vendor_name: "GreenDrive Tech",
      charged:5
    },
    {
      vehicle_id: "V012",
      no_of_trips: 47,
      trip_kms: 1125,
      avg_kms_per_day: 29,
      avg_trip_per_day: 1.9,
      avg_daily_work_hour: 8.2,
      avg_daily_charging_time: 3.7,
      co2_emission: 475,
      vendor_name: "FutureVehicles Inc.",
      charged:60
    },
    {
      vehicle_id: "V013",
      no_of_trips: 36,
      trip_kms: 825,
      avg_kms_per_day: 21,
      avg_trip_per_day: 1.3,
      avg_daily_work_hour: 6.7,
      avg_daily_charging_time: 2.6,
      co2_emission: 515,
      vendor_name: "EcoInnovate Motors",
      charged:40
    },
    {
      vehicle_id: "V014",
      no_of_trips: 53,
      trip_kms: 1225,
      avg_kms_per_day: 32,
      avg_trip_per_day: 2,
      avg_daily_work_hour: 8.8,
      avg_daily_charging_time: 4.5,
      co2_emission: 460,
      vendor_name: "Sustainable Drive Co.",
      charged:60
    },
    {
      vehicle_id: "V015",
      no_of_trips: 39,
      trip_kms: 925,
      avg_kms_per_day: 24,
      avg_trip_per_day: 1.4,
      avg_daily_work_hour: 7.5,
      avg_daily_charging_time: 3,
      co2_emission: 495,
      vendor_name: "GreenVehicles Innovations",
      charged:9
    },
    {
      vehicle_id: "V016",
      no_of_trips: 44,
      trip_kms: 1075,
      avg_kms_per_day: 26,
      avg_trip_per_day: 1.7,
      avg_daily_work_hour: 7.8,
      avg_daily_charging_time: 3.5,
      co2_emission: 485,
      vendor_name: "EcoFleet Solutions",
      charged:20
    },
    {
      vehicle_id: "V017",
      no_of_trips: 46,
      trip_kms: 1100,
      avg_kms_per_day: 28,
      avg_trip_per_day: 1.8,
      avg_daily_work_hour: 8,
      avg_daily_charging_time: 3.8,
      co2_emission: 480,
      vendor_name: "CleanMotion Autos",
      charged:50
    },
    {
      vehicle_id: "V018",
      no_of_trips: 32,
      trip_kms: 725,
      avg_kms_per_day: 20,
      avg_trip_per_day: 1.2,
      avg_daily_work_hour: 6.2,
      avg_daily_charging_time: 2.2,
      co2_emission: 540,
      vendor_name: "GreenTech Innovations",
      charged:98
    },
    {
      vehicle_id: "V019",
      no_of_trips: 42,
      trip_kms: 975,
      avg_kms_per_day: 23,
      avg_trip_per_day: 1.4,
      avg_daily_work_hour: 7,
      avg_daily_charging_time: 3,
      co2_emission: 510,
      vendor_name: "FutureDrive Autos",
      charged:65
    },
    {
      vehicle_id: "V020",
      no_of_trips: 34,
      trip_kms: 800,
      avg_kms_per_day: 22,
      avg_trip_per_day: 1.3,
      avg_daily_work_hour: 6.5,
      avg_daily_charging_time: 2.8,
      co2_emission: 525,
      vendor_name: "EcoRide Tech",
      charged:66
    },
    {
      vehicle_id: "V021",
      no_of_trips: 51,
      trip_kms: 1200,
      avg_kms_per_day: 30,
      avg_trip_per_day: 2,
      avg_daily_work_hour: 8,
      avg_daily_charging_time: 4,
      co2_emission: 500,
      vendor_name: "GreenWheels Innovations",
      charged:63
    },
    {
      vehicle_id: "V022",
      no_of_trips: 49,
      trip_kms: 1175,
      avg_kms_per_day: 29,
      avg_trip_per_day: 1.9,
      avg_daily_work_hour: 8.2,
      avg_daily_charging_time: 3.7,
      co2_emission: 475,
      vendor_name: "EcoMotion Autos",
      charged:96
    },
    {
      vehicle_id: "V023",
      no_of_trips: 37,
      trip_kms: 850,
      avg_kms_per_day: 20,
      avg_trip_per_day: 1.2,
      avg_daily_work_hour: 7,
      avg_daily_charging_time: 3,
      co2_emission: 505,
      vendor_name: "CleanDrive Tech",
      charged:70
    },
    {
      vehicle_id: "V024",
      no_of_trips: 56,
      trip_kms: 1300,
      avg_kms_per_day: 35,
      avg_trip_per_day: 2.2,
      avg_daily_work_hour: 8.5,
      avg_daily_charging_time: 4.2,
      co2_emission: 470,
      vendor_name: "FutureVehicles Innovations",
      charged:3
    },
    {
      vehicle_id: "V025",
      no_of_trips: 33,
      trip_kms: 750,
      avg_kms_per_day: 18,
      avg_trip_per_day: 1.1,
      avg_daily_work_hour: 6,
      avg_daily_charging_time: 2.3,
      co2_emission: 530,
      vendor_name: "GreenRide Autos",
      charged:87
    },
    {
      vehicle_id: "V026",
      no_of_trips: 43,
      trip_kms: 1025,
      avg_kms_per_day: 28,
      avg_trip_per_day: 1.7,
      avg_daily_work_hour: 7.8,
      avg_daily_charging_time: 3.5,
      co2_emission: 485,
      vendor_name: "EcoFusion Innovations",
      charged:63
    },
    {
      vehicle_id: "V027",
      no_of_trips: 38,
      trip_kms: 900,
      avg_kms_per_day: 22,
      avg_trip_per_day: 1.3,
      avg_daily_work_hour: 6.7,
      avg_daily_charging_time: 2.6,
      co2_emission: 515,
      vendor_name: "GreenTech Autos",
      charged:7
    },
    {
      vehicle_id: "V028",
      no_of_trips: 47,
      trip_kms: 1125,
      avg_kms_per_day: 29,
      avg_trip_per_day: 1.9,
      avg_daily_work_hour: 8.2,
      avg_daily_charging_time: 3.7,
      co2_emission: 475,
      vendor_name: "Sustainable Drive",
      charged:90
    },
    {
      vehicle_id: "V029",
      no_of_trips: 39,
      trip_kms: 925,
      avg_kms_per_day: 24,
      avg_trip_per_day: 1.4,
      avg_daily_work_hour: 7.5,
      avg_daily_charging_time: 3,
      co2_emission: 495,
      vendor_name: "EcoVehicles Tech",
      charged:75
    },
    {
      vehicle_id: "V030",
      no_of_trips: 44,
      trip_kms: 1075,
      avg_kms_per_day: 26,
      avg_trip_per_day: 1.7,
      avg_daily_work_hour: 7.8,
      avg_daily_charging_time: 3.5,
      co2_emission: 485,
      vendor_name: "GreenMotion Autos",
      charged:63
    },
  ];
export default data
